server:
 port: 8088
 
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: false
      path: /console
  jpa:
    showsql: false
    hibernate:
      ddl-auto: none 
    open-in-view: false
 
logging:
 level:
  org.springframework.security: INFO
  
oauth-server-client:
 access-token-uri: https://localhost:8443/oauth/token
 client-id: web-app
 client-secret: secret
 
resource:
  server: 
    url: http://localhost:8082