logging:
 level:
  org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:oauth;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    
  h2:
    console:
      enabled: true
      path: /console
      
  jpa:
    showsql: false
    hibernate:
      ddl-auto: none 
    open-in-view: false
   

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:server.p12
    key-store-password: 1234
    cert: server_cert.pem
    
client:
  ssl:
    cert: client_cert.pem
    key: 
    
oauth:
  server:
    url: https://localhost:8443